env: DEBUG=True
dist: xenial
language: python
python: "3.6"

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
      - hfst

cache:
  pip: true
  directories:
    - $HOME/.cache
    - node_modules # NPM packages

stages:
  - test
  - name: deploy
    if: branch = master && type = push

jobs:
  include:
    - name: "Unit Tests"
      install: pipenv install --dev
      script: pipenv run test --cov=CreeDictionary
      after_success: codecov

    - name: "Integration Tests"
      # turns out it's harder to configure python with language: node_js
      # it's easier to configure node_js with language: python instead
      install:
        - pipenv install
        - npm ci
        - npm run build
      script: npm test

    - stage: deploy
      language: minimal
      # This is not redundant. You need a 'deploy' key IN ADDITION to the
      # deploy stage :/
      deploy:
        provider: script
        script: bash ./libexec/deploy-to-sapir
