# Production docker-compose for itwewina.

version: "3"

services:
  itwewina:
    restart: always
    image: ghcr.io/ualbertaaltlab/itwewina.altlab.app:latest
    ports:
      # Why port 8001?
      # See: https://github.com/UAlbertaALTLab/deploy.altlab.dev/blob/master/docs/application-registry.tsv
      - 8001:8000
      # Note: If you want to run the Cypress tests on the staging container, use the
      # following:
      #
      # CYPRESS_BASE_URL=http://localhost:8001 npx cypress open
      #
      # See: https://docs.cypress.io/guides/guides/environment-variables.html#We-can-move-this-into-a-Cypress-environment-variable

      # uWSGI stats can be accessed here on localhost:
      - "9191:9191"
    volumes:
      - "./.env:/app/.env"

      # Mount directory, not file, so that -shm and -wal files will be
      # persisted outside the container if using WAL mode
      - "/data_local/application-data/itwewina/db/:/app/CreeDictionary/db/"

      # Mount vector models from git lfs checkout instead of building into
      # image
      - "../CreeDictionary/res/vector_models/:/app/CreeDictionary/res/vector_models/"

      # Use a persistent path for search sample results, so that they
      # remain across deployments and so that additional sample results can
      # be uploaded from other sources for comparison purposes
      - "/data_local/application-data/itwewina/search-quality/:/app/CreeDictionary/search_quality/sample_results/"
